### PR TITLE
Girls

### PR DESCRIPTION
**Pull request by yasmineashoush5**
I added the HTML to the flashcards handlebar

### CODE REVIEW

**Comment by rabia-desing** [comment]
1 => remove controllers/api/User-routes.js from your commit 
2 => In views folder except the file in layouts folder named as main.handlebars all other files show not contain any html skeleton i.e <!DOCTYPE html> all other files should start from section or div.

**Comment by jessikea** [comment]
> 1 => remove controllers/api/User-routes.js from your commit 2 => In views folder except the file in layouts folder named as main.handlebars all other files show not contain any html skeleton i.e all other files should start from section or div.

^^ yes exactly what Rabia said. Flashcards should be in partials not in the same folder as main.handlebars

**Comment by jessikea** [comment]
I'm closing this so we dont accidentally merge it.

**Review by jessikea — CHANGES_REQUESTED** [review]
you should remove User-routes.js from your commit. Also relocate the file for flashcards.

**Comment by jessikea** [comment]
I reopened it just in case it accidentally messes Yasmines branch. Do not approve until changes are made.

**Review by jessikea — COMMENTED** [review]
* make flashcards.js in public/js folder. Fix src in flashcards.handlebars. Fix home.handlebars and delete flashcard html partial you wrote.

**Pull request closed without merging**
